# -*- coding: utf-8 -*-
"""task06.py

Automatically generated by Colab.
"""

# !pip install rdflib  # Comentada según instrucciones

import rdflib
print(rdflib.__version__)

from validation import Report

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS

g = Graph()
r = Report()

ns = Namespace("http://mydomain.org#")
g.namespace_manager.bind('ns', ns, override=False)

g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
    print(s, p, o)

ontology = Namespace("http://www.oeg-upm.net/Ontology#")
person = Namespace("http://oeg.fi.upm.es/def/people#")

g.namespace_manager.bind('ontology', ontology)
g.namespace_manager.bind('person', person)

# Clases
g.add((person.Person , RDF.type, RDFS.Class))
g.add((person.Professor , RDF.type, RDFS.Class))
g.add((person.FullProfessor , RDF.type, RDFS.Class))
g.add((person.AssociateProfessor , RDF.type, RDFS.Class))
g.add((person.InterimAssociateProfessor , RDF.type, RDFS.Class))

# Etiquetas
g.add((person.Person, RDFS.label, Literal("Person", datatype=XSD.string)))
g.add((person.Professor, RDFS.label, Literal("Professor", datatype=XSD.string)))
g.add((person.FullProfessor, RDFS.label, Literal("FullProfessor", datatype=XSD.string)))
g.add((person.AssociateProfessor, RDFS.label, Literal("AssociateProfessor", datatype=XSD.string)))
g.add((person.InterimAssociateProfessor, RDFS.label, Literal("InterimAssociateProfessor", datatype=XSD.string)))

# Subclases
g.add((person.Professor, RDFS.subClassOf, person.Person))
g.add((person.FullProfessor, RDFS.subClassOf, person.Professor))
g.add((person.AssociateProfessor, RDFS.subClassOf, person.Professor))
g.add((person.InterimAssociateProfessor, RDFS.subClassOf, person.AssociateProfessor))

r.validate_task_06_01(g)

# Propiedades
g.add((person.hasName , RDF.type, RDF.Property))
g.add((person.hasHomePage , RDF.type, RDF.Property))
g.add((person.hasColleague , RDF.type, RDF.Property))

# Labels
g.add((person.hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))
g.add((person.hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))
g.add((person.hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))

# Dominios
g.add((person.hasName, RDFS.domain, person.Person))
g.add((person.hasHomePage, RDFS.domain, person.FullProfessor))
g.add((person.hasColleague, RDFS.domain, person.Person))

# Rangos
g.add((person.hasName, RDFS.range, RDFS.Literal))
g.add((person.hasColleague, RDFS.range, person.Person))
g.add((person.hasHomePage, RDFS.range, RDFS.Literal))

r.validate_task_06_02(g)

data = Namespace("http://oeg.fi.upm.es/resource/person/")

# Instancias
g.add((data.Oscar, RDF.type, person.AssociateProfessor))
g.add((data.Asun, RDF.type, person.FullProfessor))
g.add((data.Raul, RDF.type, person.InterimAssociateProfessor))

# Etiquetas
g.add((data.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((data.Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))
g.add((data.Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))

# Relaciones / propiedades
g.add((data.Oscar, person.hasName, Literal("Óscar Corcho García", datatype=XSD.string)))
g.add((data.Oscar, person.hasColleague, data.Asun))
g.add((data.Asun, person.hasColleague, data.Raul))
g.add((data.Asun, person.hasHomePage, Literal("http://www.oeg-upm.net/", datatype=XSD.string)))

r.validate_task_06_03(g)

vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
foaf = Namespace("http://xmlns.com/foaf/0.1/")

# Tipos
g.add((foaf.email , RDF.type, RDFS.Datatype))
g.add((vcard.Family , RDF.type, RDF.Property))
g.add((vcard.Given , RDF.type, RDFS.Datatype))

# Rangos
g.add((foaf.email , RDFS.range, XSD.string))
g.add((vcard.Family , RDFS.range, XSD.string))
g.add((vcard.Given , RDFS.range, XSD.string))

# Datos de Oscar
g.add((data.Oscar, foaf.email, Literal("ocorcho@fi.upm.es")))
g.add((data.Oscar, vcard.Family, Literal("Corcho García")))
g.add((data.Oscar, vcard.Given, Literal("Oscar")))

r.validate_task_06_04(g)
r.save_report("_Task_06")
